backend/protected/controllers/PengaduanController.php
<?php

class PengaduanController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
                        /*
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
                         * 
                         */
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('admin', 'index', 'view', 'create','update', 'editable', 'delete', 'all', 'pending', 'approved', 'reply'),
				'users'=>array('@'),
			),
                        /*
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
                         * 
                         */
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$comment=new CArrayDataProvider(PostsMain::model()->getComment($id));
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'comment'=>$comment
		));
	}

		/**
		 * Creates a new model.
		 * If creation is successful, the browser will be redirected to the 'view' page.
		 */
		public function actionCreate()
		{
			$model=new PostsMain;

			// Uncomment the following line if AJAX validation is needed
			// $this->performAjaxValidation($model);

			if(isset($_POST['PostsMain']))
			{
				$model->attributes=$_POST['PostsMain'];
				if($model->save())
					$this->redirect(array('view','id'=>$model->id));
			}

			$this->render('create',array(
				'model'=>$model,
			));
		}
        
		/**
		 * Reply a new model.
		 * If creation is successful, the browser will be redirected to the 'view' page.
		 */
		public function actionReply($id)
		{
			$model=new PostsMain;

			// Uncomment the following line if AJAX validation is needed
			// $this->performAjaxValidation($model);

			if(isset($_POST['PostsMain']))
			{
				$model->attributes=$_POST['PostsMain'];
				if($model->save())
					$this->redirect(array('pengaduan/view/','id'=>$id));
			}

			$this->render('reply',array(
				'model'=>$model,
				'id'=>$id
			));
		}
		
		
        public function actionAll(){
            
			$gridDataProvider = new CArrayDataProvider(PostsMain::model()->getAllPengaduan());
			$gridColumns = array(
				array('name'=>'label', 'header'=>'Title'),
				array('name'=>'content', 'header'=>'Content'),
				
				array(
					'htmlOptions' => array('nowrap'=>'nowrap'),
					'class'=>'bootstrap.widgets.TbButtonColumn',
					'template' => '{view}{delete}',
					'viewButtonUrl'=>'Yii::app()->createUrl("/pengaduan/view/", array("id"=>$data["id"]))',
					'updateButtonUrl'=>'Yii::app()->createUrl("/pengaduan/view/", array("id"=>$data["id"]))',
					'deleteButtonUrl'=>'Yii::app()->createUrl("/pengaduan/delete/", array("id"=>$data["id"]))',
				)
			);

			$this->render('all',array(
				'gridDataProvider'=>$gridDataProvider, 'gridColumns'=>$gridColumns
			));
            
        }
        
        public function actionPending(){
			$gridDataProvider = new CArrayDataProvider(PostsMain::model()->getPendingPengaduan());
			$gridColumns = array(
				array('name'=>'label', 'header'=>'Title'),
				array('name'=>'content', 'header'=>'Content'),
				
				array(
					'htmlOptions' => array('nowrap'=>'nowrap'),
					'template' => '{view}{delete}',
					'class'=>'bootstrap.widgets.TbButtonColumn',
					'viewButtonUrl'=>'Yii::app()->createUrl("/pengaduan/view/", array("id"=>$data["id"]))',
					'updateButtonUrl'=>'Yii::app()->createUrl("/pengaduan/view/", array("id"=>$data["id"]))',
					'deleteButtonUrl'=>'Yii::app()->createUrl("/pengaduan/delete/", array("id"=>$data["id"]))',
				)
			);

			$this->render('pending',array(
				'gridDataProvider'=>$gridDataProvider, 'gridColumns'=>$gridColumns
			));
        }
        
        public function actionApproved(){
			$gridDataProvider = new CArrayDataProvider(PostsMain::model()->getApprovedPengaduan());
			$gridColumns = array(
				array('name'=>'label', 'header'=>'Title'),
				array('name'=>'content', 'header'=>'Content'),
				
				array(
					'htmlOptions' => array('nowrap'=>'nowrap'),
					'class'=>'bootstrap.widgets.TbButtonColumn',
					'template' => '{view}{delete}',
					'viewButtonUrl'=>'Yii::app()->createUrl("/pengaduan/view/", array("id"=>$data["id"]))',
					'updateButtonUrl'=>'Yii::app()->createUrl("/pengaduan/update/", array("id"=>$data["id"]))',
					'deleteButtonUrl'=>'Yii::app()->createUrl("/pengaduan/delete/", array("id"=>$data["id"]))',
				)
			);

			$this->render('approved',array(
				'gridDataProvider'=>$gridDataProvider, 'gridColumns'=>$gridColumns
			));
        }

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['PostsMain']))
		{
			$model->attributes=$_POST['PostsMain'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('PostsMain');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
        
        public function actionEditable()
        {
            Yii::import('ext.editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('PostsMain');  // 'User' is classname of model to be updated
            $es->update();
        }

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
                /*
                $model = PostsMain::model()->findBySql("select * from posts where type='3'");
                $this->render('admin', array('model'=>$model));
                */
            
		$model =  PostsMain::model()->findBySql("select * from posts where type='3'");
		//$model->unsetAttributes();  // clear any default values
		if(isset($_GET['PostsMain']))
			$model->attributes=$_GET['PostsMain'];

		$this->render('admin',array(
			'model'=>$model,
		));
                 
                 
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=PostsMain::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='posts-main-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

backend/protected/views/pengaduan/_comment.php
<div class="well well-small">
<?php echo CHtml::encode($data['content']); ?>
</div>

backend/protected/views/pengaduan/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'posts-main-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->hiddenField($model,'parent_id',array('class'=>'span5', 'value'=>$id)); ?>

	<?php echo $form->hiddenField($model,'label',array('class'=>'span5','maxlength'=>512, 'value'=>'Balasan')); ?>

	<?php echo $form->hiddenField($model,'resume',array('class'=>'span5','maxlength'=>1024)); ?>

	<?php echo $form->textAreaRow($model,'content',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->hiddenField($model,'type',array('class'=>'span5','maxlength'=>64, 'value'=>5)); ?>

	<?php echo $form->hiddenField($model,'position',array('class'=>'span5', 'value'=>0)); ?>

	<?php echo $form->hiddenField($model,'permalink',array('class'=>'span5','maxlength'=>512)); ?>

	<?php echo $form->hiddenField($model,'author_id',array('class'=>'span5', 'value'=>Yii::App()->user->id)); ?>

	<?php echo $form->hiddenField($model,'author_name',array('class'=>'span5','maxlength'=>128, 'value'=>User::model()->info()->name)); ?>

	<?php echo $form->hiddenField($model,'author_email',array('class'=>'span5','maxlength'=>64, 'value'=>User::model()->info()->email)); ?>

	<?php echo $form->hiddenField($model,'status',array('class'=>'span5','maxlength'=>1, 'value'=>1)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

backend/protected/views/pengaduan/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'parent_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'label',array('class'=>'span5','maxlength'=>512)); ?>

	<?php echo $form->textFieldRow($model,'resume',array('class'=>'span5','maxlength'=>1024)); ?>

	<?php echo $form->textAreaRow($model,'content',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textFieldRow($model,'type',array('class'=>'span5','maxlength'=>64)); ?>

	<?php echo $form->textFieldRow($model,'position',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'permalink',array('class'=>'span5','maxlength'=>512)); ?>

	<?php echo $form->textFieldRow($model,'author_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'author_name',array('class'=>'span5','maxlength'=>128)); ?>

	<?php echo $form->textFieldRow($model,'author_email',array('class'=>'span5','maxlength'=>64)); ?>

	<?php echo $form->textFieldRow($model,'status',array('class'=>'span5','maxlength'=>1)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

backend/protected/views/pengaduan/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('parent_id')); ?>:</b>
	<?php echo CHtml::encode($data->parent_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('label')); ?>:</b>
	<?php echo CHtml::encode($data->label); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('resume')); ?>:</b>
	<?php echo CHtml::encode($data->resume); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('type')); ?>:</b>
	<?php echo CHtml::encode($data->type); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('position')); ?>:</b>
	<?php echo CHtml::encode($data->position); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('permalink')); ?>:</b>
	<?php echo CHtml::encode($data->permalink); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('author_id')); ?>:</b>
	<?php echo CHtml::encode($data->author_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('author_name')); ?>:</b>
	<?php echo CHtml::encode($data->author_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('author_email')); ?>:</b>
	<?php echo CHtml::encode($data->author_email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	*/ ?>

</div>

backend/protected/views/pengaduan/admin.php
<?php
$this->breadcrumbs=array(
	'Posts Mains'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List PostsMain', 'url'=>array('index')),
	array('label'=>'Create PostsMain', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('posts-main-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Posts Main</h1>

<?php 

$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'posts-main-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
                'author_id',
		//'id',
		//'parent_id',
		'label',
		//'resume',
		'content',
		//'type',
		/*
		'position',
		'permalink',
		'author_id',
		'author_name',
		'author_email',
                 * 
                 */
                
		'status',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); 

?>

backend/protected/views/pengaduan/all.php
<?php
$this->breadcrumbs=array(
	'Pengaduan'=>array('all'),
	'Manage',
);

$this->menu=array(
	//array('label'=>'List PostsMain', 'url'=>array('index')),
	//array('label'=>'Re', 'url'=>array('create')),
);
?>

<h1>Semua Pengaduan</h1>

<?php
	$this->widget('bootstrap.widgets.TbGridView', array(
		'type'=>'striped bordered',
		'dataProvider'=>$gridDataProvider,
		//'template'=>"{items}",
		'columns'=>$gridColumns,
	));
?>

backend/protected/views/pengaduan/approved.php
<?php
$this->breadcrumbs=array(
	'Pengaduan'=>array('all'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List PostsMain', 'url'=>array('index')),
	array('label'=>'Create PostsMain', 'url'=>array('create')),
);
?>

<h1>Pengaduan yang disetujui</h1>

<?php
	$this->widget('bootstrap.widgets.TbGridView', array(
		'type'=>'striped bordered',
		'dataProvider'=>$gridDataProvider,
		//'template'=>"{items}",
		'columns'=>$gridColumns,
	));
?>

backend/protected/views/pengaduan/create.php
<?php
$this->breadcrumbs=array(
	'Posts Mains'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List PostsMain','url'=>array('index')),
	array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>Create PostsMain</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

backend/protected/views/pengaduan/index.php
<?php
$this->breadcrumbs=array(
	'Posts Mains',
);

$this->menu=array(
	array('label'=>'Create PostsMain','url'=>array('create')),
	array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>Posts Mains</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

backend/protected/views/pengaduan/pending.php
<?php
$this->breadcrumbs=array(
	'Pengaduan'=>array('all'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List PostsMain', 'url'=>array('index')),
	array('label'=>'Create PostsMain', 'url'=>array('create')),
);
?>

<h1>Pengaduan Belum Disetujui</h1>

<?php
	$this->widget('bootstrap.widgets.TbGridView', array(
		'type'=>'striped bordered',
		'dataProvider'=>$gridDataProvider,
		//'template'=>"{items}",
		'columns'=>$gridColumns,
	));
?>

backend/protected/views/pengaduan/reply.php
<?php
$this->breadcrumbs=array(
	'Pengaduan'=>array('all'),
	'Reply',
);

$this->menu=array(
	//array('label'=>'List PostsMain','url'=>array('index')),
	//array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>Reply Pegaduan</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'id'=>$id)); ?>

backend/protected/views/pengaduan/update.php
<?php
$this->breadcrumbs=array(
	'Posts Mains'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List PostsMain','url'=>array('index')),
	array('label'=>'Create PostsMain','url'=>array('create')),
	array('label'=>'View PostsMain','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>Update PostsMain <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

backend/protected/views/pengaduan/view.php
<?php
$this->breadcrumbs=array(
	'Pengaduan'=>array('all'),
	$model->id,
);

$this->menu=array(
	//array('label'=>'List PostsMain','url'=>array('index')),
	array('label'=>'Reply','url'=>array('reply', 'id'=>$model->id)),
	//array('label'=>'Update PostsMain','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	//array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>View Pengaduan</h1>

<table class="table table-bordered">
    <tr>
        <td>Author</td>
        <td>
            <?php
                echo $model->author->name;
            ?>
        </td>
    </tr>
    <tr>
        <td>Subject</td>
        <td>
            <?php
                echo $model->label;
            ?>
        </td>
    </tr>
    <tr>
        <td>Content</td>
        <td>
            <?php
                echo $model->content;
            ?>
        </td>
    </tr>
    <tr>
        <td>Status</td>
        <td>
            <?php 

                $this->widget('ext.editable.EditableField', array(
                    'type'      => 'select',
                    'model'     => $model,
                    'attribute' => 'status',
                    'url'       => $this->createUrl('pengaduan/editable'),  //url for submit data
                    'placement' => 'right',
                    'source'    => array(1 => 'Approved', 2 => 'Pending'),
                ));

            ?>
        </td>
    </tr>
</table>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$comment,
	'itemView'=>'_comment',
)); ?>