backend/protected/models/Posts.php
<?php

/**
 * This is the model class for table "posts".
 *
 * The followings are the available columns in table 'posts':
 * @property integer $id
 * @property integer $parent_id
 * @property string $label
 * @property string $resume
 * @property string $content
 * @property string $type
 * @property integer $position
 * @property string $permalink
 * @property integer $author_id
 * @property string $author_name
 * @property string $author_email
 * @property string $status
 *
 * The followings are the available model relations:
 * @property User $author
 * @property TermsRelationships[] $termsRelationships
 */
class Posts extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Posts the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'posts';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('parent_id, position, author_id', 'numerical', 'integerOnly'=>true),
			array('label, permalink', 'length', 'max'=>512),
			array('resume', 'length', 'max'=>1024),
			array('type, author_email', 'length', 'max'=>64),
			array('author_name', 'length', 'max'=>128),
			array('status', 'length', 'max'=>1),
			array('content', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, parent_id, label, resume, content, type, position, permalink, author_id, author_name, author_email, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'author' => array(self::BELONGS_TO, 'User', 'author_id'),
			'termsRelationships' => array(self::HAS_MANY, 'TermsRelationships', 'posts_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'parent_id' => 'Parent',
			'label' => 'Label',
			'resume' => 'Title',
			'content' => 'Content',
			'type' => 'Type',
			'position' => 'Position',
			'permalink' => 'Permalink',
			'author_id' => 'Author',
			'author_name' => 'Author Name',
			'author_email' => 'Author Email',
			'status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('parent_id',$this->parent_id);
		$criteria->compare('label',$this->label,true);
		$criteria->compare('resume',$this->resume,true);
		$criteria->compare('content',$this->content,true);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('position',$this->position);
		$criteria->compare('permalink',$this->permalink,true);
		$criteria->compare('author_id',$this->author_id);
		$criteria->compare('author_name',$this->author_name,true);
		$criteria->compare('author_email',$this->author_email,true);
		$criteria->compare('status',$this->status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function getParent(){
            $model = Yii::app()->db->createCommand()
                    ->select('id, label')
                    ->from('posts')
                    ->where("parent_id='22031989' or id='1' or id='22031989'")
                    ->order('id asc')
                    ->queryAll();
            return $model;
        }
}

backend/protected/models/PostsType.php
<?php

/**
 * This is the model class for table "posts_type".
 *
 * The followings are the available columns in table 'posts_type':
 * @property integer $id
 * @property string $name
 * @property string $status
 */
class PostsType extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return PostsType the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'posts_type';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'length', 'max'=>128),
			array('status', 'length', 'max'=>1),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('status',$this->status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function getPostsType(){
            $model = Yii::app()->db->createCommand()
                    ->select('id, label')
                    ->from('posts_type')
                    ->where("id in (1, 2, 4)")
                    ->order('id asc')
                    ->queryAll();
            return $model;
        }
}

backend/protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	public function actionAll()
	{
		$this->render('all');
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

backend/protected/controllers/PostsController.php
<?php

class PostsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update', 'delete', 'all', 'editable'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
                $this->redirect('http://dishub.ptdpa.com/post/id/'.$id);
                /*
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
                */
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new PostsMain;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['PostsMain']))
		{
			$model->attributes=$_POST['PostsMain'];
			if($model->save())
				//$this->redirect(array('view','id'=>$model->id));
                            $this->redirect(array('all'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['PostsMain']))
		{
			$model->attributes=$_POST['PostsMain'];
			if($model->save())
				$this->redirect(array('all'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}
        
        public function actionEditable()
        {
            Yii::import('ext.editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('PostsMain');  // 'User' is classname of model to be updated
            $es->onBeforeUpdate = function($event) {
                $event->sender->setAttribute('date_modified', date('Y-m-d'));
            };
            $es->update();
        }

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('PostsMain');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new PostsMain('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['PostsMain']))
			$model->attributes=$_GET['PostsMain'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
        
        public function actionAll(){
            
		$model=new PostsMain('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['PostsMain']))
			$model->attributes=$_GET['PostsMain'];

		$this->render('all',array(
			'model'=>$model,
		));
            
        }

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=PostsMain::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='posts-main-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

backend/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
        //$this->getAction()->getId()=='login'?public $layout='//layouts/column2left':public $layout='//layouts/column3map';
        /*
        if($this->getAction()->getId()=='login'){
            public $layout='//layouts/column2left';
        }
        else{
            public $layout='//layouts/column3map';
        }
        */
	/**
	 * Declares class-based actions.
	 */
        public $layout = '//layouts/column3';
    
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
                        'article'=>array(
                                'class'=>'CViewAction'
                        )
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
        $model = Berita::model()->getLatestNews();
		$this->render('index', array('model'=>$model));
		//$this->render('index');
	}
        
        public function actionArticle($id){
            $this->render('article');
        }
        

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
                    echo $error['message'];
	    	else
                    $this->render('error', $error);
                    //$this->redirect(array('site/index'));
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
                
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model = Posts::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

backend/protected/views/posts/_add.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'posts-main-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>
        Categories
        <?php echo $form->hiddenField($model,'terms_id'); ?>
        <?php
            $this->widget('ext.editable.EditableField', array(
                'type' => 'select',
                'model' => $model,
                'attribute' => 'terms_id',
                'url' => $this->createUrl('posts/create'),
                'source' => CHtml::listData(Terms::model()->findAll(), 'id', 'label'), 
                'onUpdate' => 'js: function(e, editable) {
                                   $("#PostsMain_terms_id").val(editable.value);
                               }',
                'placement' =>  'right'
            ));
        ?>
        <br /><br />

        Parent
        <?php echo $form->hiddenField($model,'parent_id'); ?>
        <?php
            $this->widget('ext.editable.EditableField', array(
                'type' => 'select',
                'model' => $model,
                'attribute' => 'parent_id',
                'url' => $this->createUrl('posts/create'),
                'source' => CHtml::listData(Posts::model()->getParent(), 'id', 'label'), 
                'onUpdate' => 'js: function(e, editable) {
                                   $("#PostsMain_parent_id").val(editable.value);
                               }',
                'placement' =>  'right'
            ));
        ?>
        <br /><br />

	<?php echo $form->textFieldRow($model,'label',array('class'=>'span5','maxlength'=>512)); ?>

	<?php echo $form->ckEditorRow($model,'resume',array('options'=>array('fullpage'=>'js:true', 'height'=>'100', 'resize_maxWidth'=>'640','resize_minWidth'=>'320'))); ?>

	<?php echo $form->ckEditorRow($model,'content',array('options'=>array('fullpage'=>'js:true', 'resize_maxWidth'=>'640','resize_minWidth'=>'320'))); ?>
        <br /><br />
        <?php echo $form->textAreaRow($model,'tags',array('class'=>'span5')); ?>
        <br /><br />
        Type
        <?php echo $form->hiddenField($model,'type'); ?>
        <?php
            $this->widget('ext.editable.EditableField', array(
                'type' => 'select',
                'model' => $model,
                'attribute' => 'type',
                'url' => $this->createUrl('posts/create'),
                'source' => CHtml::listData(PostsType::model()->getPostsType(), 'id', 'label'), 
                'onUpdate' => 'js: function(e, editable) {
                                   $("#PostsMain_type").val(editable.value);
                               }',
                'placement' =>  'right'
            ));
        ?>
        <br /><br />

	<?php echo $form->textFieldRow($model,'position',array('class'=>'span5', 'value'=>0)); ?>
        
        

	<?php echo $form->textFieldRow($model,'permalink',array('class'=>'span5','maxlength'=>512)); ?>

	<?php echo $form->hiddenField($model,'author_id',array('class'=>'span5', 'value'=>Yii::app()->user->id)); ?>

	<?php echo $form->hiddenField($model,'author_name',array('class'=>'span5','maxlength'=>128, 'value'=>Yii::app()->user->get()->name)); ?>

	<?php echo $form->hiddenField($model,'author_email',array('class'=>'span5','maxlength'=>64, 'value'=>Yii::app()->user->get()->email)); ?>

	<?php echo $form->hiddenField($model,'status',array('class'=>'span5','maxlength'=>1, 'value'=>'1')); ?>


	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

backend/protected/views/posts/admin.php
<?php
$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'All',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('posts-main-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Posts
<?php echo CHtml::link('Add New', array('posts/create/'), array('class'=>'btn btn-primary')); ?>
</h1>
<!--
<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>
-->
<?php //echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'posts-main-grid',
	'dataProvider'=>new CActiveDataProvider('PostsMain',array(
		'criteria'=>array('condition'=>'type=1'))),
	'filter'=>$model,
	'columns'=>array(		
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
		//'id',
		//'parent_id',
		array(
			'class' => 'bootstrap.widgets.TbEditableColumn',
			'name' => 'label',
			'sortable'=>false,
			'editable' => array(
                                'type'  => 'text',
				'url' => $this->createUrl('posts/editable'),
				'placement' => 'left',
				//'inputclass' => 'span3'
			)
		),
		//'resume',
		//'content',
		
		/*
		'position',
		'permalink',
		'author_id',
                 * 
                 */
		'author_name',
            
		array(
			'class' => 'bootstrap.widgets.TbEditableColumn',
			'name' => 'terms_id',
			'sortable'=>false,
			'editable' => array(
                                'type'  => 'select',
				'url' => $this->createUrl('posts/editable'),
                                'source' => CHtml::listData(Categories::model()->findAll(), 'id', 'label'),
				'placement' => 'left',
				//'inputclass' => 'span3'
			)
		),
                 
		//'author_email',
		array(
			'class' => 'bootstrap.widgets.TbEditableColumn',
			'name' => 'type',
			'sortable'=>false,
			'editable' => array(
                                'type'  => 'select',
				'url' => $this->createUrl('posts/editable'),
                                'source' => CHtml::listData(PostsType::model()->findAll(), 'id', 'label'),
				'placement' => 'left',
				//'inputclass' => 'span3'
			)
		),
                'date_modified'
	),
)); ?>

backend/protected/views/posts/all.php
<?php
$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'All',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('posts-main-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Posts
<?php echo CHtml::link('Add New', array('posts/create/'), array('class'=>'btn btn-primary')); ?>
</h1>
<!--
<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>
-->
<?php //echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'posts-main-grid',
	'dataProvider'=>new CActiveDataProvider('PostsMain',array(
		'criteria'=>array('condition'=>'type=1 or type=2 or type=4'))),
	'filter'=>$model,
	'columns'=>array(		
                array(
                        'htmlOptions' => array('nowrap'=>'nowrap'),
                        'class'=>'bootstrap.widgets.TbButtonColumn',
                        //'template' => '{view}{delete}',
                        'viewButtonUrl'=>'Yii::app()->createUrl("/posts/view/", array("id"=>$data["id"]))',
                        'updateButtonUrl'=>'Yii::app()->createUrl("/posts/update/", array("id"=>$data["id"]))',
                        'deleteButtonUrl'=>'Yii::app()->createUrl("/posts/delete/", array("id"=>$data["id"]))',
                ),
		//'id',
		//'parent_id',
		array(
			'class' => 'bootstrap.widgets.TbEditableColumn',
			'name' => 'label',
			'sortable'=>false,
			'editable' => array(
                                'type'  => 'text',
				'url' => $this->createUrl('posts/editable'),
				'placement' => 'left',
				//'inputclass' => 'span3'
			)
		),
		//'resume',
		//'content',
		
		/*
		'position',
		'permalink',
		'author_id',
                 * 
                 */
		'author_name',
            
		array(
			'class' => 'bootstrap.widgets.TbEditableColumn',
			'name' => 'terms_id',
			'sortable'=>false,
			'editable' => array(
                                'type'  => 'select',
				'url' => $this->createUrl('posts/editable'),
                                'source' => CHtml::listData(Categories::model()->findAll(), 'id', 'label'),
				'placement' => 'left',
				//'inputclass' => 'span3'
			)
		),
                 
		//'author_email',
		array(
			'class' => 'bootstrap.widgets.TbEditableColumn',
			'name' => 'type',
			'sortable'=>false,
			'editable' => array(
                                'type'  => 'select',
				'url' => $this->createUrl('posts/editable'),
                                'source' => array(1 => 'Posts', 2 => 'Links', 4 => 'Pages'),
				'placement' => 'left',
				//'inputclass' => 'span3'
			)
		),
                'date_modified'
	),
)); ?>

backend/protected/views/posts/create.php
<?php
$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Add New',
);

$this->menu=array(
	array('label'=>'List PostsMain','url'=>array('index')),
	array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>Add New Posts</h1>

<?php echo $this->renderPartial('_add', array('model'=>$model)); ?>

backend/protected/views/posts/index.php
<?php
$this->breadcrumbs=array(
	'Posts Mains',
);

$this->menu=array(
	array('label'=>'Create PostsMain','url'=>array('create')),
	array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>Posts Mains</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

backend/protected/views/posts/view.php
<?php
$this->breadcrumbs=array(
	'Posts Mains'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List PostsMain','url'=>array('index')),
	array('label'=>'Create PostsMain','url'=>array('create')),
	array('label'=>'Update PostsMain','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete PostsMain','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage PostsMain','url'=>array('admin')),
);
?>

<h1>View PostsMain #<?php echo $model->id; ?></h1>

<?php 
    
    $this->widget('bootstrap.widgets.TbEditableDetailView',array(
            'data'=>$model,
            'url' => $this->createUrl('posts/editable'),  //common submit url for all editables
            'attributes'=>array(
                    //'id',
                    //'parent_id',
                    'label',
                    //'resume',
                    'content',
                    'type',
                    //'position',
                    //'permalink',
                    //'author_id',
                    //'author_name',
                    //'author_email',
                    array(  //select loaded from database
                        'name' => 'status',
                        'editable' => array(
                            'type' => 'select',
                            'source' => CHtml::listData(Status::model()->findAll(), 'id', 'label')
                         )
                    ),
            ),
    )); 
    
    /*
    $this->widget('bootstrap.widgets.TbEditableDetailView', array(
        'id' => 'region-details',
        'data' => PostsMain::model()->findByPk(23),
        'url' => $this->createUrl('site/editable'),  //common submit url for all editables
        'attributes'=>array(
                'label',
                'content',
        )
    ));
     * 
     */
?>