backend/protected/models/User.php
<?php

/**
 * This is the model class for table "user".
 *
 * The followings are the available columns in table 'user':
 * @property integer $id
 * @property string $username
 * @property integer $role_id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $last_name
 *
 * The followings are the available model relations:
 * @property Posts[] $posts
 * @property Role $role
 */
class User extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
        public $password2;
        
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
                        array('role_id, username, password, password2, name, email', 'required'),
			array('role_id', 'numerical', 'integerOnly'=>true),
			array('username', 'length', 'max'=>32),
			array('name', 'length', 'max'=>128),
			array('email, last_name', 'length', 'max'=>64),
			array('password', 'length', 'max'=>256),
                        array('password2', 'length', 'max'=>256),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('alamat, pekerjaan','type','type'=>'string','allowEmpty'=>true),
			array('id, username, role_id, name, email, password, password2, last_name, alamat', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'posts' => array(self::HAS_MANY, 'Posts', 'author_id'),
			'role' => array(self::BELONGS_TO, 'Role', 'role_id'),
		);
	}
        
        
        public function beforeSave() {

            if(parent::beforeSave() && $this->isNewRecord) {

                $this->password = md5($this->password);

            }

            return true;
        }
        
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Username <i>(Required)</i>',
			'role_id' => 'Role',
			'name' => 'Name',
			'email' => 'E-Mail <i>(Required)</i>',
			'password' => 'Password <i>(Twice, Required)</i>',
                        'password2' => 'Re-type Password',
			'last_name' => 'Last Name',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('role_id',$this->role_id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('password',$this->password,true);
                $criteria->compare('password2',$this->password,true);
		$criteria->compare('last_name',$this->last_name,true);
		$criteria->compare('alamat',$this->alamat,true);

		
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function info(){
	
		$user = User::model()->findByPk(Yii::App()->user->id);
		return $user;
	
	}
	

}

backend/protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	//public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
                        /*
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
                        */
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index', 'admin', 'create','update', 'editable', 'view', 'profile'),
				'users'=>array('@'),
			),
                        /*
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
                         * 
                         */
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
                $model=new User;
                // collect user input data
                if(isset($_POST['User']))
                {
                    $password1 = $_POST['User']['password'];
                    $password2 = $_POST['User']['password2'];
                    
                    if($password1==$password2){

                        // Uncomment the following line if AJAX validation is needed
                        $this->performAjaxValidation($model);

                        if(isset($_POST['User']))
                        {
                                $model->attributes=$_POST['User'];
                                if($model->save())
                                        $this->redirect(array('view','id'=>$model->id));
                        }
                    }
                }

                    $this->render('create',array(
                            'model'=>$model,
                    ));
                
                
	}
        
        public function actionProfile(){
            $id = Yii::App()->user->getId();
            $model = $this->loadModel($id);
            $this->render('profile', array('model'=>$model));
        }

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('view',array(
			'model'=>$model,
		));
	}
        
        public function actionEditable()
        {
            Yii::import('ext.editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('User');  // 'User' is classname of model to be updated
            $es->onBeforeUpdate = function($event) {
                $event->sender->setAttribute('password', md5('User[password]'));
            };
            $es->update();
        }

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
            /*
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
             * 
             */
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

backend/protected/views/user/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-form',
	'enableAjaxValidation'=>true,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="control-group">
            <label class="control-label">
		<?php echo $form->labelEx($model,'username'); ?>
            </label>
            <div class="controls">
		<?php echo $form->textField($model,'username',array('size'=>32,'maxlength'=>32, 'class'=>'span4')); ?>
            </div>
            <div class="control-label">
		<?php echo $form->error($model,'username'); ?>
            </div>
	</div>
        
        
	<div class="control-group">
            <label class="control-label">
		<?php echo $form->labelEx($model,'email'); ?>
            </label>
            <div class="controls">
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>64, 'class'=>'span4')); ?>
            </div>
            <label class="control-label">
		<?php echo $form->error($model,'email'); ?>
            </label>
	</div>

	<div class="control-group">
            <label class="control-label">
		<?php echo $form->labelEx($model,'name'); ?>
            </label>
            <div class="controls">
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128, 'class'=>'span4')); ?>
            </div>
            <label class="control-label">
		<?php echo $form->error($model,'name'); ?>
            </label>
	</div>

	<div class="control-group">
            <label class="control-label">
		<?php echo $form->labelEx($model,'last_name'); ?>
            </label>
            <div class="controls">
		<?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>64, 'class'=>'span4')); ?>
            </div>
            <label class="control-label">
		<?php echo $form->error($model,'last_name'); ?>
            </label>
	</div>

	<div class="control-group">
            <label class="control-label">
		<?php echo $form->labelEx($model,'password'); ?>
            </label>
            <div class="controls">
		<?php echo $form->passwordField($model,'password',array('size'=>60,'maxlength'=>256, 'class'=>'span4')); ?>
            </div>
            <label class="control-label">
		<?php echo $form->error($model,'password'); ?>
            </label>
	</div>
        
        <div class="control-group">
            <label class="control-label">
                <?php echo $form->labelEx($model,'password2'); ?>
            </label>
            <div class="controls">
                <?php echo $form->passwordField($model,'password2', array('class'=>'span4')); ?>
            </div>
            <label class="control-label">
                <?php echo $form->error($model,'password2'); ?>
            </label>
        </div>
        
	<div class="control-group">
            <label class="control-label">
		<?php echo $form->labelEx($model,'role_id'); ?>
            </label>
            <div class="controls">
		<?php echo $form->hiddenField($model,'role_id'); ?>
                <?php
                    $this->widget('ext.editable.EditableField', array(
                        'type' => 'select',
                        'model' => $model,
                        'attribute' => 'role_id',
                        'url' => $this->createUrl('user/create'),
                        'source' => CHtml::listData(Role::model()->findAll(), 'id', 'name'), 
                        'onUpdate' => 'js: function(e, editable) {
                                           $("#User_role_id").val(editable.value);
                                       }',
                        'placement' =>  'right',
                        'emptytext'=>'Add user role here'
                    ));
                ?>
            </div>
            <label class="control-label">
		<?php echo $form->error($model,'role_id'); ?>
            </label>
	</div>

	<div class="control-group">
            <div class="controls">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class'=>'btn-primary')); ?>
            </div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

backend/protected/views/user/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>32,'maxlength'=>32)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'role_id'); ?>
		<?php echo $form->textField($model,'role_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>64)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'last_name'); ?>
		<?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>64)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

backend/protected/views/user/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('role_id')); ?>:</b>
	<?php echo CHtml::encode($data->role_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('password')); ?>:</b>
	<?php echo CHtml::encode($data->password); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_name')); ?>:</b>
	<?php echo CHtml::encode($data->last_name); ?>
	<br />


</div>

backend/protected/views/user/admin.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('user-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Users</h1>

<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'username',
		'name',
                //'last_name',
		'email',
		array(
                    'name'      =>  'role_id',
                    'header'    =>  'Role',
                    //'filter'    =>  $data->role->name,
                    'value'=> '$data->role->name'
                ),
		//'password',
		/*
		'last_name',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

backend/protected/views/user/all.php
<?php
$this->breadcrumbs=array(
	'User'=>array('/user'),
	'All',
);?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

backend/protected/views/user/create.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Add New User</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

backend/protected/views/user/current.php
<?php
$this->breadcrumbs=array(
	'User'=>array('/user'),
	'Current',
);?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

backend/protected/views/user/index.php
<?php
$this->breadcrumbs=array(
	'Users',
);

$this->menu=array(
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Users</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

backend/protected/views/user/new.php
<?php
$this->breadcrumbs=array(
	'User'=>array('/user'),
	'New',
);?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

backend/protected/views/user/profile.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Update User', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete User', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h3>View User</h3>

<table class="table">
    <tr>
        <td>Username</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'username',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
                'placement'  => 'right'
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>First Name</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'name',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>Last Name</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'last_name',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>Email</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'email',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>Role</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'select',
                'model'     => $model,
                'attribute' => 'role_id',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
                'source' => CHtml::listData(Role::model()->findAll(), 'id', 'name'),
                'placement' =>  'right'
            ));

            ?>
        </td>
    </tr>
</table>

<h3>About Yourself</h3>
<table>
    <tr>
        <td>Password</td>
        <td>
            <?php 

                $this->widget('ext.editable.EditableField', array(
                    'type'      => 'text',
                    'model'     => $model,
                    'attribute' => 'password',
                    'url'       => $this->createUrl('user/editable'),  //url for submit data
                    'placement'  => 'right'
                ));

            ?> 
            If you would like to change the password type a new one. Otherwise leave this blank.
        </td>
    </tr>
</table>

backend/protected/views/user/update.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'View User', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>Update User <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

backend/protected/views/user/view.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Update User', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete User', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h3>View User</h3>

<table class="table">
    <tr>
        <td>Username</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'username',
                'url'       => $this->createUrl('backend/user/editable'),  //url for submit data
                'placement'  => 'right'
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>First Name</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'name',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>Last Name</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'last_name',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>Email</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'text',
                'model'     => $model,
                'attribute' => 'email',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
            ));

            ?>
        </td>
    </tr>
    <tr>
        <td>Role</td>
        <td>
            <?php 

            $this->widget('ext.editable.EditableField', array(
                'type'      => 'select',
                'model'     => $model,
                'attribute' => 'role_id',
                'url'       => $this->createUrl('user/editable'),  //url for submit data
                'source' => CHtml::listData(Role::model()->findAll(), 'id', 'name'),
                'placement' =>  'right'
            ));

            ?>
        </td>
    </tr>
</table>

<h3>About User</h3>
<table>
    <tr>
        <td>Password</td>
        <td>
            <?php 

                $this->widget('ext.editable.EditableField', array(
                    'type'      => 'text',
                    'model'     => $model,
                    'attribute' => 'password',
                    'url'       => $this->createUrl('user/editable'),  //url for submit data
                    'placement'  => 'right'
                ));

            ?> 
            If you would like to change the password type a new one. Otherwise leave this blank.
        </td>
    </tr>
</table>